### ISSUE TITLE
Update to 1.20.6 Please

### ISSUE THREAD

**Issue by sternschnaube** [gbl/StepUp#18]
java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_49477(float)'
	at com.nottoomanyitems.stepup.StepChanger.onEndTick(StepChanger.java:39)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$ela000$fabric-lifecycle-events-v1$onEndTick(class_310.java:14247)
	at net.minecraft.class_310.method_1574(class_310.java:2063)
	at net.minecraft.class_310.method_1523(class_310.java:1281)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by venaminecraft** [comment]
Updated version: https://modrinth.com/mod/stepupagain/version/1.20.6-fabric0.98.0-1.4
Thanks @derrod 😊
